
preprocessor_module:
  _target_: franka_allegro.preprocess.Preprocessor
  data_path: /data/christmas_box/
  modules:
    robot: ${robot_cfg}
    image: ${image_cfg} # - this is only for tactile training
    tactile: ${tactile_cfg}
  dump_data_indices: true
  process_single_demo: false

robot_cfg:
  _target_: franka_allegro.preprocess.RobotPreprocessor
  subsample_separately: true
  robot_names: ['allegro', 'franka']
  robot_thresholds: # If robot thresholds are set to 0 then it will basically not subsample
    hand: 0.005
    arm: 0.01 # corresponding thresholds to the robot_names
  dump_fingertips: true

image_cfg:
  _target_: franka_allegro.preprocess.ImagePreprocessor
  camera_id: 0
  is_ssl: false
  time_difference: 1 # If the there is no set time difference we will not apply preprocessing for images

tactile_cfg:
  _target_: franka_allegro.preprocess.TouchPreprocessor

