_target_: franka_allegro.deployers.VINN
data_path: ???

# Directories to change by the user depending on where they saved the data
deployment_dump_dir: ???
tactile_out_dir: /home/aadhithya/Workspace/tactile-learning/franka_allegro/out/2023.12.11/09-16_sponge_picking_tactile
tactile_model_type: byol
image_out_dir: /home/aadhithya/Workspace/tactile-learning/franka_allegro/out/2023.12.10/21-49_sponge_picking
image_model_type: temporal_ssl

nn_buffer_size: 50
nn_k: 25
data_representations: ${data_representations}
representation_types: ['image', 'tactile'] # Observations used in the representations
representation_importance: [0.5, 1] # We will multiply the distances with these given numbers when using in scaled nearest neighbors
demos_to_use:  [221] # Let's use all LOL
# demos_to_use: [3]

view_num: 0
open_loop: false

dump_deployment_info: false