# TAVI
image_out_dir: /home/aadhithya/Workspace/tactile-learning/tactile_learning//home/aadhithya/Workspace/tactile-learning/tactile_learning/out/2023.11.16/00-07_finger_gaiting_temporal_ssl
image_model_type: temporal

# Joint Temporal
# image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.06.07/15-13_temporal_ssl_card_turning_view_0_joint_resnet
# image_model_type: temporal

# Contrastive Temporal
# image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.06.07/14-21_temporal_ssl_card_turning_view_0_contrastive_resnet
# image_model_type: temporal

# BYOL
# image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.06.07/17-44_image_byol_card_turning_view_0_resnet
# image_model_type: byol

# BC 
# image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.06.07/21-37_bc_card_turning_view_0_resnet
# image_model_type: bc

# image_out_dir: null
# image_model_type: pretrained

vinn_image_out_dir: 2023.06.07-17-45_image_byol_card_flipping_view_0_resnet
vinn_image_model_type: byol

data_path: /data/generalization/honda_finger_gait_working/demonstration_38/

name: finger_gaiting
task_name: HondaFingerGait-v1
camera_num: 1

expert_demo_nums: [38]
arm_offset_scale_factor: 0.08
hand_offset_scale_factor: 0.08 #sponge flipping
offset_mask: [1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0] # sponge flipping

action_type: robot