image_out_dir: /home/irmak/Workspace/tactile-learning/franka_allegro/out/2023.10.24/12-33_generalization_temporal_ssl
image_model_type: temporal 

vinn_image_out_dir: null
vinn_image_model_type: byol

data_path: /data/generalization/irmak_cp

name: generalization_pinch_grasp
task_name: GeneralizationPinchGrasp-v1
camera_num: 0

expert_demo_nums: [6] # [24]
hand_offset_scale_factor: 0.3 
arm_offset_scale_factor: 0.2
offset_mask: [0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0]

action_type: robot
