# TAVI
image_out_dir: /home/aadhithya/Workspace/tactile-learning/franka_allegro/out/2024.01.04/11-12_block_rotate #/home/aadhithya/Workspace/tactile-learning/franka_allegro/out/2024.01.05/02-45_sponge_slide #/home/aadhithya/Workspace/tactile-learning/franka_allegro/out/2023.12.19/15-24_sponge_picking_final_3_image
image_model_type: temporal

# Joint Temporal
# image_out_dir: /home/irmak/Workspace/tactile-learning/franka_allegro/out/2023.06.07/15-13_temporal_ssl_card_turning_view_0_joint_resnet
# image_model_type: temporal

# Contrastive Temporal
# image_out_dir: /home/irmak/Workspace/tactile-learning/franka_allegro/out/2023.06.07/14-21_temporal_ssl_card_turning_view_0_contrastive_resnet
# image_model_type: temporal

# BYOL
# image_out_dir: /home/irmak/Workspace/tactile-learning/franka_allegro/out/2023.06.07/17-44_image_byol_card_turning_view_0_resnet
# image_model_type: byol

# BC 
# image_out_dir: /home/irmak/Workspace/tactile-learning/franka_allegro/out/2023.06.07/21-37_bc_card_turning_view_0_resnet
# image_model_type: bc

# image_out_dir: null
# image_model_type: pretrained

tactile_out_dir: /home/aadhithya/Workspace/tactile-learning/franka_allegro/out/2024.01.05/13-27_rotate_object
tactile_model_type: byol

vinn_image_out_dir: null
vinn_image_model_type: byol

data_path: /data/object_rotate/
name: object_rotate
task_name: ObjectRotate-v1
camera_num: 0

expert_demo_nums: [30]
arm_offset_scale_factor: 0.0
hand_offset_scale_factor: 0.1 #sponge flipping
offset_mask: [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0] # sponge flipping

action_type: robot