image_out_dir: /home/aadhithya/Workspace/tactile-learning/franka_allegro/out/2023.12.14/13-26_tea_picking_temporal_ssl 
image_model_type: temporal 

tactile_out_dir: /home/aadhithya/Workspace/tactile-learning/franka_allegro/out/2023.12.13/18-03_tea_picking_tactile_byol
tactile_model_type: byol

vinn_image_out_dir: /home/aadhithya/Workspace/tactile-learning/franka_allegro/out/2023.12.14/10-48_tea_picking_image_byol
vinn_image_model_type: byol 

data_path: /data/honda_demos/tea_picking

name: tea_picking
task_name: TeaPicking-v1
camera_num: 0

expert_demo_nums: [6]
arm_offset_scale_factor: 0.00
hand_offset_scale_factor: 0.15
offset_mask: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]

action_type: robot
