_target_: franka_allegro.datasets.TactileCurvedSSLDataset
data_path: ???
tactile_information_type: whole_hand # whole_hand, stacked, single_sensor
tactile_img_size: ${tactile_image_size} 
duration: 120