_target_: franka_allegro.deployers.OpenLoop
data_path: ???
apply_hand_states: false # For fingers touching yourself this should be true
demo_to_run: ${demo_to_run}
data_representations: ${data_representations}